### ISSUE TITLE
callback support for calling client side functions from server

### ISSUE THREAD

**Issue by Argee88** [Ezelia/eureca.io#11]
Hi,
it's a great module and it has helped me out a lot already. However I'm running into a problem:

I'm trying to call a client-function from the server and provide a callback to work with the returned data. I'll extend the http://eureca.io/ example here accordingly:

**server side**

```javascript
//we need to allow bar() function first
var eurecaServer = new EurecaServer({allow:['bar']});

// ... server initialisation
eurecaServer.exports.foo = function () {
     //when a server side function is called
     //we can access the client connection
     //throught this.connection

     var conn = this.connection;
     var client = eurecaServer.getClient(conn.id);
     console.log('called foo()');
     client.bar(function(data){
          console.log(data); // should log 'callback executed' to the console
     });
}
//... other stuff
```

**client side**

```javascript
client.exports.bar = function (callback){
     console.log('called bar()');
     callback('callback executed');
}

client.ready(function (proxy) {
     proxy.foo();
});
```

Is this already possible? I couldn't get that to work.

Right now I am calling an additional server-side-function inside the client's bar function to send some data back...

**Comment by alaa-eddine** [comment]
Hi, 
unfortunately this is not supported. and can cause some security issues.
what you are trying to do here, is to transport the source code of callback function from client to server and execute it in the server side! 
this is not RPC : in RPC model, the server code and client code don't move they are just invoked remotely. 

There are allways ways to get around such situations, but I can't figure out what you are trying to do from your example.

The most common case is when you have some asynchronous code in one side, and want to ensure that the callback is executed when the asynchronous job has finished. 
if this is your issue, there is allready a solution 

if you want to use eureca.io async mode your code become :

```javascript
//server side 
...
     client.bar.onReady(function(data){
          console.log(data); // will log log 'Client code Finished' 
     });
...

client.exports.bar = function (){
     var context = this;
     context.async = true;

     console.log('called bar()');
     do_your_client_side_stuff(); 
     //you can have nested async code, here I use a setTimeout to simulate it
     setTimeout(function() {
          context.return('Client code Finished');  // when the job is finished we call context.return to trigger onReady in the server side
     }, 1000);
}

```

The async mode don't alter the way you get the returned data, it only delay the onRedy callback and give you control over it, you can trigger the onReturn at any time using context.return in the remote side.

take a look at asyn example https://github.com/Ezelia/eureca.io/tree/master/examples/5-async-returns

**Comment by Argee88** [comment]
AWESOME! Thank you, I can work with that. It's not beautiful but it works.

Thanks for the fast answer as well :+1: :)
