### ISSUE TITLE
exmple of EurecaServer inheritence

### ISSUE THREAD

**Issue by amitport** [Ezelia/eureca.io#12]
I think the way you define the server's interface using the eurecaServer object is very nice. It looks conceptually extendable. I.e., it seems that it should be possible to add new functionality to a eurecaServer using deep prototype inheritance (need to deep copy properties such as 'exports' I guess).

is it possible?
can you add such example?

Thanks!

**Comment by alaa-eddine** [comment]
if you use TypeScript extending the server is very simple


```javascript
class MyExtendedServer extends Eureca.Server {
    constructor(public settings: any = {}) {
        super(settings); // this is mandatory if you want to add custom stuff to your constructor
        //... your custom constructor stuff goes here
    }
    
    //here you can add your own methods or extend existing ones.
}
```

the only constraint you have is when you want to extend an existing method, make sure to call the superclass method so the server logic will not be broken.


that being said, before extending the server, think twice if it's really what you want, because in most cases it's much simpler to use Eureca.Server as an internal variable instead of superclass.
this way you can encapsulate the calls as you wish without any constraint.

**Comment by alaa-eddine** [comment]
if you use inheritance like the example above, you don't have to care about .exports namespace :)
the only condition to respect is to keep attach() method untouched of if you want to extend it call the superclass attach like this


```
class MyExtendedServer extends Eureca.Server {
    constructor(public settings: any = {}) {
        super(settings); // this is mandatory if you want to add custom stuff to your constructor
        //... your custom constructor stuff goes here
    }

    //here you can add your own methods or extend existing ones.

   public attach (server:any) {
        super.attach(server); 

        //your custom code
   }
}


```

**Comment by amitport** [comment]
Thanks for the detailed response!

BTW, just for completeness, I think that for imitating the typescript inheritance this JS code will be good enough:
```js
MyExtendedServer.prototype = Object.create(Eureca.Server.prototype, {
    constructor: {
      value: MyExtendedServer ,
      enumerable: false,
      writable: true,
      configurable: true
    }
  }) 
```

(and then calling `Eureca.Server.apply(this, arguments)` and `Eureca.Server.prototype.attach.apply(this, arguments)` in the constructor and the attache method correspondingly)

**Comment by alaa-eddine** [comment]
yes seems good to me.
I use a quite similar syntax for vanilla JS inheritance.
```javascript
function MyExtendedServer() {
    Eureca.Server.apply(this, arguments);
    // ...
}
MyExtendedServer.prototype.attach = function(server) {
    Eureca.Server.prototype.attach.apply(this, arguments);
    // ...
};
MyExtendedServer.prototype = Object.create(Eureca.Server.prototype);
MyExtendedServer.prototype.constructor = MyExtendedServer;
```
