### ISSUE TITLE
where is eureca.js?

### ISSUE THREAD

**Issue by henryalejo** [Ezelia/eureca.io#13]
Hi I'm newbie on nodejs, I check eureca.io and it is a good job, I'm trying to do a web app but your examples have a file eureca.js.  where can I get this file? , thanks

**Comment by alaa-eddine** [comment]
the file is dynamically served by eureca.io server so you don't have to care about it.
just refer it with /eureca.js and it will be downloaded by the client browser :)

**Comment by henryalejo** [comment]
Thanks a lot, It  worked , when I sent  the file index.thml with  res.sendfile, eureca.js is created !!
app.get('/', function (req, res, next) {
    res.sendfile('index.html');   
});
