### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by kanecko** [Ezelia/eureca.io#17]
Hello Ezelia.

What are your plans for the future here? Can we expect this project becoming more active?

**Comment by alaa-eddine** [comment]
Hi @kanecko ,
eureca.io is not dead at all ! as you can see, the last dev commit was three months ago, and issues are fixed as quick as possible.
the current version is stable enougth and we are using it on our internal projects for production.
the goal till v0.7 is to stabilize the current features and complete the documentation (http://eureca.io/doc/ )
for now I'm the only maintainer of the project, this is why the updates are not frequent, but I try to keep it as stable as possible and up to date.

if you encounter any specific bug, please don't hesitate to open an issue, I'll do my best to fix is asap :)

**Comment by kanecko** [comment]
Ah, I see! For some reason I thought it wasn't stable yet since the documentation is WIP.
I might be using your library in the near future.

**Comment by alaa-eddine** [comment]
the documentation is work in progress because it need some time to document every aspect of eureca.io, but general use cases are already documented and examples are provided in this repository :)
