### ISSUE TITLE
Desynchronization with repeated async function calls.

### ISSUE THREAD

**Issue by Fiveside** [Ezelia/eureca.io#20]
I'm experiencing a desynchronization with async server calls such that the caller and callee are not always paired properly when the first call is not complete by the time the second call reaches the server.  For example: if I have a server function that takes 150 ms to complete, but its invoked every 100 ms, the promise returned from the first invocation may return the result from the second invocation.  

Here's a demonstration of what I'm experiencing.  The client just pings the server and checks the result to verify that it got back what it sent:

server.js
```javascript
var http = require('http');
var httpServer = http.createServer();
var Eureca = require('eureca.io');
var eurecaServer = new Eureca.Server();
eurecaServer.attach(httpServer);

eurecaServer.exports.ping = function(id) {
  var context = this;
  context.async = true;
  setTimeout(function() {
    context.return(id)
  }, 150)
}

console.log('Server started');
httpServer.listen(8000);
```

client.js
```javascript
﻿var Eureca = require('eureca.io');
var client = new Eureca.Client({ uri: 'ws://localhost:8000/'});

var id = 0;
function uniqueId() {
  return id++;
}

client.ready(function (proxy) {
    setInterval(function() {
      var expected = uniqueId()
      console.log("Sending " + expected);
      proxy.ping(expected).then(function(result) {
        if (expected === result) {
          console.log("Server ponged OK.");
        } else {
          console.log("Server ponged Error (" + expected + " != " + result +")");
        }
      })
    }, 100);
});
```

Client output:
```
$ node client.js
* using primus:engine.io
ws://localhost:8000/ eureca.io
Server ponged Error (1 != 0)
Server ponged Error (2 != 1)
Server ponged Error (3 != 2)
Server ponged Error (4 != 3)
Server ponged Error (5 != 4)
Server ponged Error (6 != 5)
```

It appears to return the result of the calculation to the most recently invoked call rather than the one that originally triggered the calculation.  Is there something I'm doing wrong here that might trigger this behavior?

**Comment by alaa-eddine** [comment]
Hi,
The strange behaviour you are noticing  comes from your code :) 
more precisely due to expected variable scope.
variables scopes inside setInterval callbacks is tricky, I'll try to explain.

in the following code 
```javascript
    setInterval(function() {
      var expected = uniqueId()
      console.log("Sending " + expected);
      proxy.ping(expected).then(function(result) {
        if (expected === result) {
          console.log("Server ponged OK.");
        } else {
          console.log("Server ponged Error (" + expected + " != " + result +")");
        }
      })
    }, 100);
```

you are updating expected variable each 100ms, and using it as argument for ping
ping take 150ms to finish ...
during this period, expected variable has updated ! 
ping return the result throught the promise, and then you compare the returned result to the new "expected" value ===> it's normal to have a different value here.

so to workaround the scope issue you can use this code

```javascript
    setInterval(function() {
      var expected = uniqueId()
      console.log("Sending " + expected);
      (function(_expected) {
      proxy.ping(_expected).then(function(result) {
        if (_expected=== result) {
          console.log("Server ponged OK.");
        } else {
          console.log("Server ponged Error (" + _expected + " != " + result +")");
        }
      })
      })(expected)
    }, 100);
```

**Comment by Fiveside** [comment]
Sorry for my late reply, the holidays got the better of me...

I believe this is still a problem.  The `expected` variable is being closed on because it is defined and instantiated inside the `setInterval` callback.  So the variable is not updated on each interval because an entirely new variable is created and closed over each time.  Any inner anonymous functions created bind over the correct `expected` variable.  Either way, I've updated my code sample with your adjustments, and it still reports errors:

```
Sending 0
Sending 1
Server ponged Error (1 != 0)
Sending 2
Server ponged Error (2 != 1)
Sending 3
Server ponged Error (3 != 2)
Sending 4
Server ponged Error (4 != 3)
Sending 5
Server ponged Error (5 != 4)
```

Replacing the `proxy.ping` invocation with a simple promise based solution produces the expected output.  Here's the mock that I've been using to test this:
```javascript
function mockPing(id) {
  return new Promise(function(resolve) {
    setTimeout(function() {
      resolve(id);
    }, 150);
  });
}
``` 

Also looks like I accidentally left some syntax errors in my example code in the initial post.  I've updated the samples so that they now run out of the box.  Sorry about that.

**Comment by alaa-eddine** [comment]
This should be fixed now :) 
please check https://github.com/Ezelia/eureca.io/issues/22 for details.

**Comment by Fiveside** [comment]
Fantastic!

I've tested out the changes and it does fix the problem.  Thank you!

**Comment by alaa-eddine** [comment]
Good news :) 
I updated the official package on npm yesterday btw
