### ISSUE TITLE
eureca.io not installing using npm

### ISSUE THREAD

**Issue by jimcute** [Ezelia/eureca.io#21]
Hello,

I am trying to install eureca.io on my windows 10 PC,  but getting some error:
You can see below screenshot for more details about my issue:

http://screencast.com/t/jSuKQ7jkTw1x

Anybody is there to take me out from this issue.

**Comment by alaa-eddine** [comment]
Hi @jimcute ,
I just managet to make a test on windows 10 with nodejs v 5.3.0 and its working fine for me.

can you please update nodejs and test again.
please also check your npm version, mine is 3.3.12 .

**Comment by jimcute** [comment]
Yes its working.

Problem was in nodejs version.

Thanks a lot.
