### ISSUE TITLE
Access socket object during authenticate call

### ISSUE THREAD

**Issue by Dreaded-Gnu** [Ezelia/eureca.io#26]
Hello,
I'm using the authenticate option of eureca.io. The authentication process within my project works like this:
- User requests a token from an external login server
- User tries to authenticate at game server with token from login server

The token is a jwt, which will be checked within the authenticate method. When the token is valid, I need to store the user id from game. This is necessary to determine the user later on, when a server side method is called from client.

Before I've started switching from socket.io to eureca.io I've stored the user token within the socket object on the server after successful authentication.

Is it possible to access the socket object within the authentication callback I set, when initializing eureca server? Or do I have to write my own authentication "middleware" for this use case?

example:
`var eureca_server = new Eureca.Server( { authenticate: function( token, next ) { /** check token & store user id within socket on server for later rpc calls */ next(); } } );`

**Comment by alaa-eddine** [comment]
Hi, 
thank you for reporting this :)  I modified the code so we can get access to a context (similar to other calls) which give access to client socket.

usage example 

```
var eureca_server = new Eureca.Server( { 
authenticate: function( token, next ) { 
    var socket = this.socket; // access client socket here 

 next(); } } );

```

**Comment by alaa-eddine** [comment]
this update is still not available on npm, so please use the github repository or replace the two files in node_modules/eureca.io/lib with those ones https://github.com/Ezelia/eureca.io/tree/master/lib in your

**Comment by alaa-eddine** [comment]
was closed by mistake, I'll wait you to test and confirm before closing.

**Comment by Dreaded-Gnu** [comment]
Thank you for the fast response. 
I'll test the change this evening.

**Comment by Dreaded-Gnu** [comment]
Tested it, and works fine.
I'll close the issue then.
