### ISSUE TITLE
client.ready not executed if client is already ready

### ISSUE THREAD

**Issue by DenianArthurShades** [Ezelia/eureca.io#29]
After some debugging in my project, I found out that any client.ready callback that is added after the client is ready will not be executed. I currently have to disable autoconnect and manually call client.connect after all callbacks are added.

It would be nice if any callbacks defined "late" could just be executed immediately.

**Comment by alaa-eddine** [comment]
Hi @DenianArthurShades ,  
Why are you calling the ready callback after the client is ready ? can you please give me more details about your use case ?

the ready event is intended to detect the ready state when it occures, there is maybe a possibility to let it trigger immediately if the client is already ready, but first I need to understand well your issue :)

**Comment by DenianArthurShades** [comment]
I'm using eureca in combination with angular. I load eureca first and initialize the client.

Inside one of my angular services, I need the server Proxy - which, the way I understand your documentation, I can only get in the ready callback. Now, if I leave autoconnect enabled, I get a race condition:
- If my angular service is initialized before the eureca client is ready, the callback is executed and I get my data
- If the eureca client is ready first, the callback is _not_ executed, I _don't_ get my data and the app crashes.

I already tried just passing the server proxy to a predefined global variable, but that also failed for some reason, so I'm stuck with the callback.

**Comment by alaa-eddine** [comment]
Actually there is also an exposed client.serverProxy member which give access to the server proxy,  otherwise it returns null.  See http://eureca.io/doc/Client.html (members section) 

Is this what you are looking for?

**Comment by alaa-eddine** [comment]
Please also see isReady()  method documentation in the same page,  it contains a basic usage example.

**Comment by DenianArthurShades** [comment]
Ah, ok... yes, it is. Still awkward to use, though, as you have to do something like `if (client.isReady()) { client.serverProxy.echo('hello'); } else { client.ready(function(serverProxy) { serverProxy.echo('hello'); });`, which is a strange mix of synchronous and asynchronous code. I mean, yeah, I can work with it as it is. I just assumed that client.ready should work kind of like promise.then - "if the client is ready, use the callback now, otherwise use it whenever the client is ready".

Still, I can think of situations where the current behaviour is better, I just made a wrong assumption. Thanks for your help!

**Comment by alaa-eddine** [comment]
I'm actually working on a harmonization of eureca.io syntax, and the client.ready call is one of syntaxes I'm thinking to optimize.

as you said, there are situations when we need to know exactly when the client is ready ... maybe I need to separate the usages, making client ready execute each time if the client is already ready, and add a new event listener which trigger only once when the client get connected and ready.
