### ISSUE TITLE
Pack client side javascript

### ISSUE THREAD

**Issue by Dreaded-Gnu** [Ezelia/eureca.io#35]
Hello,
I am trying to develop a multiplayer game by using eureca. On a later state of the development, I want do deliver an executable by using electron or something familiar.

So my question is, can I pack the client side javascript of eureca also into an electron app?

**Comment by Dreaded-Gnu** [comment]
To understand why I am asking that question: I want to deliver all client side javascript within a single file, so that I just have to load one script instead of multiple scripts.

At the moment I pack phaser and my game code into a bundle, and I want to have the eureca client code also within this bundle.

**Comment by alaa-eddine** [comment]
Hi @Dreaded-Gnu ,
you can pack the content of eureca.js file in your bundle, 
but beware, some changes in the server side can make it impossible to the clients to connect, the content of eureca.js is generated on the fly to garantee the client to have the right libraries to talk with the server.

changes that can impact the generated eureca.js are the transport library choice, and listening port (in case you are not explicitely specifying it in your client code) .

if you're sure those settings will not change when you distribute your client, you're fine with the content of eureca.js packed in your bundle :)

**Comment by Dreaded-Gnu** [comment]
Hello,
I close the issue. Achieved it to pack it, but at the end, i came up with the solution to not packing it.
