### ISSUE TITLE
How return a promise

### ISSUE THREAD

**Issue by campanagerald** [Ezelia/eureca.io#42]
Hi. I would like to ask how return a promise.

example:

---- this is my server
eurecaServer.exports.getAllBooks: () => {
      return bluebird.coroutine(function*() {
        try {
          let document = yield opp.viewAllBooks() // return a a list of books
          return document
        } catch (error) {

          // internal server error
          return {error: error.message}
        }
      })()
    }

---- this is my client

client.ready(function (serverProxy) {

  //the onReady event is triggered when the remote side finishes
  //executing the called function.
  //returned value is stored in result argument
  serverProxy.getAllBooks().onReady(function(result) {
    console.log(result);
  });
});

the result is always an object: { isFulfilled: false, isRejected: false }

**Comment by alaa-eddine** [comment]
Hi @campanagerald,
please check the async-returns example here : https://github.com/Ezelia/eureca.io/tree/master/examples/5-async-returns 

it let you take control of the server response, and decide when to return it.

btw, I invite you to replace onReady() syntax with then() syntax, which is accepted by eureca.io and more normalized to promises.

**Comment by campanagerald** [comment]
@alaa-eddine thank you sir, it works. This is what i did

getAllBooks: function() {
      
      let context:any = this
      context.async = true
      
      bluebird.coroutine(function*() {
        try {
          let document = yield opp.viewAllBooks()
          context.return(document)
        } catch (error) {
          // internal server error
          return { error: error.message }
        }
      })()
    }

**Comment by alaa-eddine** [comment]
@campanagerald awesome ! if it's a public service you can share about it here ... I'm planing to add a list of services using eureca.io on the official web site (http://eureca.io).

I'm closing this issue since it's resolved :)
