### ISSUE TITLE
Dealing with server disconnect on the client

### ISSUE THREAD

**Issue by fyyyyy** [Ezelia/eureca.io#8]
Hey, im using eureca in [this project](http://www.tabloro.com) and it works really well.
If do get a server shutdown & restart, e.g. i'm pushing a new build, how would i detect that on the client side ?

Thanks

**Comment by alaa-eddine** [comment]
hi @fyyyyy really greate project :)
I will share it on our FB page (https://www.facebook.com/Ezelia.games) ;)

about your issue, if the server disconnect for few seconds to few minutes, the client will try to automatically reconnect to the server, you don't have to do anything.

if you really want to detect disconnection/retries events (for example to display notify the user) you can use onConnectionLost, onConnectionRetry and onDisconnect see this example: https://github.com/Ezelia/eureca.io/blob/master/examples/99-bidirectional-calls/client.js

**Comment by fyyyyy** [comment]
ok, thanks for sharing :)
Cool that's what i need :+1:
