### ISSUE TITLE
Dynos on Heroku - synch

### ISSUE THREAD

**Issue by fyyyyy** [Ezelia/eureca.io#9]
Do you have some experience with scaling to multiple dynos on heroku ?
I believe they do not share memory, and since we store  game sessions mostly in memory, this would probably not be synchronized across dynos ?
Cheers

**Comment by alaa-eddine** [comment]
well, there is no way to share memory between many servers/nodes ... what you can do is sharing data (using redis or mongodb instance for example).
then synchronize your dynos logic using eureca.io.
nothing prevent you from running an eureca.io server AND eureca.io client from the same script.
this way, your server script can also be a client of another eurecaServer. (see node clients in examples codes).
for security, you'll need to prevent external clients to call internal (server-to-server) methods.

**Comment by fyyyyy** [comment]
Yes, i guess i need to write some load balancing logic to distribute players across different instances

**Comment by codingmaven** [comment]
@fyyyyy How did you implement load balancing logic to distribute traffic across difference instances?

**Comment by fyyyyy** [comment]
I didnt :) Runs well enough on a high spec instance
